name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js 16 (or the required version)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can change this to the version required by your project

      - name: NPM Install
        run: npm install

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Docker build and push
        run: |
          docker build -t swiggy-clone .
          docker tag swiggy-clone ${{ secrets.DOCKERHUB_USERNAME }}/swiggy-clone:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/swiggy-clone:latest
        env:
          DOCKER_CLI_ACI: 1
      - name: Try to stop and remove existing container (if any)
        run: |
          docker stop swiggy-clone || echo "Container not running, skipping stop."
          docker rm swiggy-clone || echo "Container not found, skipping removal."

  deploy:
     needs: build
     runs-on: [self-hosted]
     steps:
        - name: docker pull image
          run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/swiggy-clone:latest
        - name: Image scan
          run: trivy image ${{ secrets.DOCKERHUB_USERNAME }}/swiggy-clone:latest > trivyimagedeploy.txt
        - name: Deploy to container
          run: docker run -d --name swiggy-clone -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/swiggy-clone:latest
        - name: Update kubeconfig
          run: aws eks --region eu-north-1 update-kubeconfig --name EKS_CLOUD
        - name: Deploy to kubernetes
          run: kubectl apply -f deployment-service.yml
